(#%require "Graphics.rkt")
(define window (make-window 405 405 "test"))
((window 'set-background!) "red")
(define layer (window 'make-layer))
(define tile (make-tile 400 400))
((tile 'draw-rectangle) 0 0 400 400 "blue")
((layer 'add-drawable) tile)
((tile 'set-x!) 0)
((tile 'set-y!) 0)